---
abstract: 'Middleware to provide LemonLDAP support for Plack applications'
author:
  - 'Renee Bäcker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-LemonLDAP-BasicAuth
requires:
  MIME::Base64: 0
  Plack: 0
  Plack::Middleware::Auth::Basic: 0
  SOAP::Lite: 0
  parent: 0
  perl: 5.008008
version: 0.01
